### ISSUE TITLE
Results on `c2rust`-generated program

### ISSUE THREAD

**Issue by shinmao** [rustanlys/rupta#11]
I tried to run rupta on the generated program of `c2rust`, which could have large number of `unsafe extern "C"` in files. The behavior of rupta is werid that it just finished the execution right away without any error message or outputs.
```sh
cargo-pta pta -- --entry parseit --dump-pts pts.txt
```
The project doesn't have main function, which is kind of `lib`. So I set entry function as `parseit`.  

Is there any limitation of rupta leads to this behavior? Currently, I am not able to debug the reason.

**Comment by LeeeWee** [comment]
Is it convenient for you to share the generated `parseit` program? It would help us better figure out the issue.

**Comment by shinmao** [comment]
Sure. The attach is the cargo project where I run `cargo-pta` in it. It might not be compilable; however, it just stop execution without any error message.

[pta-test.zip](https://github.com/user-attachments/files/17913663/pta-test.zip)

**Comment by LeeeWee** [comment]
Currently, rupta does not analyze staticlib and rlib, which causes it to terminate execution quickly. To analyze the `parseit` program, you can add "lib" to the `crate-type` in the `Cargo.toml` file.:
```
crate-type = ["lib", "staticlib", "rlib"]
```

**Comment by shinmao** [comment]
@LeeeWee Thanks. I make it.

**Comment by LeeeWee** [comment]
Is `as_mut_bytes` defined in this crate? Currently only functions defined within the crate can be specified as the entry function.

**Comment by shinmao** [comment]
Yes. The function is defined as the link provided above.

**Comment by LeeeWee** [comment]
This issue occurs when analyzing a library and there are multiple test targets. I have fixed this issue in the latest commit.

**Comment by LeeeWee** [comment]
Please add `--lib` after `cargo-pta pta`:
```
cargo-pta pta --lib -- --entry-func as_mut_bytes --pta-type cs --context-depth 1 --dump-call-graph cg.dot --dump-pts pts.txt
```

There are additional issues to address. `as_mut_bytes` is an associate function. I found that there are two `as_mut_bytes` functions defined in the `header.rs` file: one associated with the `Header` struct and one associated with the `GnuExtSparseHeader` struct. A random one will be selected as the entry function.
