### ISSUE TITLE
Unable to run rupta framework

### ISSUE THREAD

**Issue by koushik0329** [rustanlys/rupta#8]
When I tried to run RUPTA for a single file using the binary pta, I am getting an error
The command used to run rupta is
```
pta /tests/unit_tests/alloc.rs --pta-type cs --dump-pts .
```
output is
```
pta: error while loading shared libraries: librustc_driver-40c0e4619dd444d7.so: cannot open shared object file: No such file or directory
```
rust version used is(rustup --version )
```
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.77.0-nightly (bf3c6c5be 2024-02-01)`
```

**Comment by LeeeWee** [comment]
Please try setting the environment variable `export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH` in the rupta directory.

**Comment by koushik0329** [comment]
Thank you sir.

**Comment by koushik0329** [comment]
When I tried to run the command 
```
$ pta <path-to-file> --entry <entry-function-name> --pta-type <pta-type> --context-depth <N> --dump-call-graph <call-graph-path> --dump-pts <pts-path>
```

I am getting an error that says 
```
error: Unrecognized option: 'entry'
```
I wanted to dump pts and call graph for sync.rs in **/atuin/crates/atuin/tests/sync.rs** in **atuin**

The command used is
```
pta /home/koushik/atuin/crates/atuin/tests/sync.rs --entry sync --pta-type cs --context-depth 1 --dump-call-graph /home/koushik/rupta/tests/unit_tests/alloc_call_graph.dot --dump-pts /home/koushik/rupta/tests/unit_tests/alloc_pts2.txt
```
The output is 
```
error: Unrecognized option: 'entry'
```

I also tried the command 
```
pta /home/koushik/atuin/crates/atuin/tests/sync.rs --entry sync() --pta-type cs --context-depth 1 --dump-call-graph /home/koushik/rupta/tests/unit_tests/alloc_call_graph.dot --dump-pts /home/koushik/rupta/tests/unit_tests/alloc_pts2.txt
```

The output is 
```
bash: syntax error near unexpected token `('
```

**Comment by LeeeWee** [comment]
It is a mistake in README. The option for specifying the entry function should be `--entry-func` instead of `--entry`.

**Comment by koushik0329** [comment]
Are there any other options for ```<pta-type>``` other than cs and ander

and can we dump any other graphs rather than call graph and pts ?

**Comment by LeeeWee** [comment]
Currently, only `cs` and `ander` have been well tested in our framework, and no graphs other than the call graph can be dumped.
